{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9e5bbcd5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================================================\n",
      "🚀 شروع فرآیند استخراج و تبدیل داده\n",
      "============================================================\n",
      "📥 مرحله 1: خواندن داده از SQL Server...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\pishva_r\\AppData\\Local\\Temp\\ipykernel_32128\\1784534852.py:50: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(query, conn)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ داده با موفقیت از SQL خوانده شد. تعداد رکوردها: 145,315\n",
      "🔄 مرحله 2: تغییر استراکچر داده...\n",
      "🔢 تعداد AssetIDهای یکتا: 12\n",
      "   پردازش 1,000 رکورد...\n",
      "   پردازش 2,000 رکورد...\n",
      "   پردازش 3,000 رکورد...\n",
      "   پردازش 4,000 رکورد...\n",
      "   پردازش 5,000 رکورد...\n",
      "   پردازش 6,000 رکورد...\n",
      "   پردازش 7,000 رکورد...\n",
      "   پردازش 8,000 رکورد...\n",
      "   پردازش 9,000 رکورد...\n",
      "   پردازش 10,000 رکورد...\n",
      "   پردازش 11,000 رکورد...\n",
      "   پردازش 12,000 رکورد...\n",
      "✅ تعداد رکوردهای پردازش شده: 12,144\n",
      "🧹 مرحله 3: حذف ردیف‌های دارای مقادیر خالی...\n",
      "   حذف 61 ردیف دارای مقادیر خالی\n",
      "📅 مرحله 4: تبدیل زمان‌ها...\n",
      "💾 مرحله 5: ذخیره در فایل اکسل...\n",
      "✅ فایل با موفقیت ذخیره شد: second_stage_inputs\\G11\\dsas_g11_generator_bearings_output.xlsx\n",
      "📊 تعداد رکوردهای نهایی: 12,083\n",
      "📋 تعداد ستون‌ها: 16\n",
      "\n",
      "📊 اطلاعات آماری:\n",
      "   بازه تاریخ: 2021-03-16 05:33:48 تا 2026-06-28 20:30:34\n",
      "   تعداد AssetIDها: 12\n",
      "\n",
      "📋 نمونه‌ای از داده‌ها:\n",
      "    id AssetID_9343 AssetID_9344 AssetID_9357 AssetID_9362 AssetID_9363  \\\n",
      "1    1        110.0         32.0         16.0         53.0         18.0   \n",
      "2    2         96.0         26.0         28.0         55.0         18.0   \n",
      "3    3        102.0         27.0         24.0         55.0         19.0   \n",
      "5    4         33.0         13.0         25.0         64.0         17.0   \n",
      "6    5        107.0          7.0         17.0         58.0         20.0   \n",
      "7    6        108.0          5.0         15.0         57.0         20.0   \n",
      "8    7        110.0          5.0         12.0         54.0         20.0   \n",
      "9    8        112.0          5.0         10.0         54.0         20.0   \n",
      "10   9        109.0          3.0         13.0         52.0         19.0   \n",
      "11  10         96.0          7.0         23.0         58.0         20.0   \n",
      "\n",
      "   AssetID_9364 AssetID_9365 AssetID_9366 AssetID_9367 AssetID_9371  \\\n",
      "1          49.0         27.0         19.0         14.0         66.0   \n",
      "2          52.0         28.6         20.3         13.0         65.0   \n",
      "3          55.0         28.0         22.0         13.0         61.0   \n",
      "5          46.0         25.0         28.0          8.0         61.0   \n",
      "6          67.0         39.0         29.0         10.0         56.0   \n",
      "7          68.0         38.0         29.0         11.0         55.0   \n",
      "8          58.0         29.0         22.0         13.0         61.0   \n",
      "9          57.0         28.0         21.0         13.0         63.0   \n",
      "10         52.0         28.0         24.0         13.0         64.0   \n",
      "11         58.0         29.0         27.0         12.0         60.0   \n",
      "\n",
      "   AssetID_9372 AssetID_9373                date  RecordDate RecordTime  \n",
      "1          65.0         58.0 2021-03-16 05:33:48  2021-03-16   05:33:48  \n",
      "2          58.0         54.0 2021-03-17 08:53:42  2021-03-17   08:53:42  \n",
      "3          60.0         54.0 2021-03-18 06:03:54  2021-03-18   06:03:54  \n",
      "5          61.0         55.0 2021-03-19 08:31:17  2021-03-19   08:31:17  \n",
      "6          55.0         50.0 2021-03-20 17:37:26  2021-03-20   17:37:26  \n",
      "7          54.0         50.0 2021-03-20 19:48:19  2021-03-20   19:48:19  \n",
      "8          60.0         53.0 2021-03-20 22:54:09  2021-03-20   22:54:09  \n",
      "9          62.0         55.0 2021-03-21 02:07:30  2021-03-21   02:07:30  \n",
      "10         56.0         53.0 2021-03-21 04:46:30  2021-03-21   04:46:30  \n",
      "11         60.0         54.0 2021-03-21 07:36:54  2021-03-21   07:36:54  \n",
      "\n",
      "============================================================\n",
      "✅ فرآیند با موفقیت کامل شد!\n",
      "============================================================\n",
      "\n",
      "📋 لیست ستون‌های فایل خروجی:\n",
      "    1. id\n",
      "    2. AssetID_9343\n",
      "    3. AssetID_9344\n",
      "    4. AssetID_9357\n",
      "    5. AssetID_9362\n",
      "    6. AssetID_9363\n",
      "    7. AssetID_9364\n",
      "    8. AssetID_9365\n",
      "    9. AssetID_9366\n",
      "   10. AssetID_9367\n",
      "   11. AssetID_9371\n",
      "   12. AssetID_9372\n",
      "   13. AssetID_9373\n",
      "   14. date\n",
      "   15. RecordDate\n",
      "   16. RecordTime\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import pyodbc\n",
    "import os\n",
    "\n",
    "def get_sql_connection():\n",
    "    \"\"\"ایجاد اتصال به SQL Server\"\"\"\n",
    "    return pyodbc.connect(\n",
    "        'DRIVER={SQL Server};'\n",
    "        'SERVER=MKZ-DSAS\\\\DSAS;'\n",
    "        'DATABASE=DSAS;'\n",
    "        'UID=datadriven;'\n",
    "        'PWD=5Rdx@4Rfv1362'\n",
    "    )\n",
    "\n",
    "def fetch_and_transform_data():\n",
    "    \"\"\"\n",
    "    خواندن داده از SQL Server، تغییر استراکچر و ذخیره در فایل اکسل\n",
    "    \"\"\"\n",
    "    \n",
    "    # مرحله 1: خواندن داده از SQL Server\n",
    "    print(\"📥 مرحله 1: خواندن داده از SQL Server...\")\n",
    "    \n",
    "    query = \"\"\"\n",
    "    SELECT TOP (10000000) [ID]\n",
    "          ,[AssetID]\n",
    "          ,[UnitID]\n",
    "          ,[Value]\n",
    "          ,[RecordTime]\n",
    "          ,[RecordDate]\n",
    "          ,[PersonelID]\n",
    "          ,[OutofRange]\n",
    "          ,[ValueType]\n",
    "          ,[MobileID]\n",
    "          ,[DateTime]\n",
    "          ,[TimeStamp]\n",
    "          ,[Job]\n",
    "          ,[IsDeleted]\n",
    "          ,[ShiftCode]\n",
    "          ,[OnTime]\n",
    "    FROM [DSAS].[PDA].[Periodic_Values]\n",
    "    WHERE [UnitID]=11 AND\n",
    "    ([AssetID]=9357 OR [AssetID]=9343 OR [AssetID]=9344 OR [AssetID]=9362 OR \n",
    "     [AssetID]=9363 OR [AssetID]=9364 OR [AssetID]=9365 OR [AssetID]=9366 OR \n",
    "     [AssetID]=9367 OR [AssetID]=9371 OR [AssetID]=9372 OR [AssetID]=9373)\n",
    "    \"\"\"\n",
    "    \n",
    "    try:\n",
    "        conn = get_sql_connection()\n",
    "        df = pd.read_sql(query, conn)\n",
    "        conn.close()\n",
    "        print(f\"✅ داده با موفقیت از SQL خوانده شد. تعداد رکوردها: {len(df):,}\")\n",
    "    except Exception as e:\n",
    "        print(f\"❌ خطا در خواندن داده از SQL: {e}\")\n",
    "        return None\n",
    "    \n",
    "    # مرحله 2: تغییر استراکچر داده (همانند کد اول)\n",
    "    print(\"🔄 مرحله 2: تغییر استراکچر داده...\")\n",
    "    \n",
    "    # استخراج AssetIDهای یکتا\n",
    "    unique_ids = df['AssetID'].unique().tolist()\n",
    "    print(f\"🔢 تعداد AssetIDهای یکتا: {len(unique_ids)}\")\n",
    "    \n",
    "    # ساخت دیتافریم خروجی با ستون‌های مورد نظر\n",
    "    columns = ['TimeStamp'] + [f'AssetID_{uid}' for uid in unique_ids]\n",
    "    output_df = pd.DataFrame(columns=columns)\n",
    "    \n",
    "    # پردازش تکراری تا خالی شدن دیتافریم اصلی\n",
    "    row_count = 0\n",
    "    while not df.empty and unique_ids:\n",
    "        main_id = unique_ids[0]\n",
    "        main_subset = df[df['AssetID'] == main_id]\n",
    "        \n",
    "        if main_subset.empty:\n",
    "            unique_ids.pop(0)\n",
    "            continue\n",
    "        \n",
    "        # گرفتن اولین ردیف از AssetID اصلی\n",
    "        main_row = main_subset.iloc[0]\n",
    "        main_ts = main_row['TimeStamp']\n",
    "        main_value = main_row['Value']\n",
    "        used_indices = [main_row.name]\n",
    "        \n",
    "        # پیدا کردن نزدیک‌ترین TimeStamp برای سایر AssetIDها\n",
    "        row_data = {'TimeStamp': main_ts, f'AssetID_{main_id}': main_value}\n",
    "        \n",
    "        for other_id in unique_ids[1:]:\n",
    "            subset = df[df['AssetID'] == other_id].copy()\n",
    "            if subset.empty:\n",
    "                row_data[f'AssetID_{other_id}'] = np.nan\n",
    "                continue\n",
    "            \n",
    "            subset['ts_diff'] = np.abs(subset['TimeStamp'] - main_ts)\n",
    "            close_rows = subset[subset['ts_diff'] <= 1800]\n",
    "            \n",
    "            if not close_rows.empty:\n",
    "                closest_row = close_rows.sort_values('ts_diff').iloc[0]\n",
    "                row_data[f'AssetID_{other_id}'] = closest_row['Value']\n",
    "                used_indices.append(closest_row.name)\n",
    "            else:\n",
    "                row_data[f'AssetID_{other_id}'] = np.nan\n",
    "        \n",
    "        # حذف ردیف‌های استفاده‌شده\n",
    "        df.drop(index=used_indices, inplace=True)\n",
    "        \n",
    "        # اضافه کردن ردیف جدید به خروجی\n",
    "        output_df = pd.concat([output_df, pd.DataFrame([row_data])], ignore_index=True)\n",
    "        row_count += 1\n",
    "        \n",
    "        # نمایش پیشرفت\n",
    "        if row_count % 1000 == 0:\n",
    "            print(f\"   پردازش {row_count:,} رکورد...\")\n",
    "    \n",
    "    print(f\"✅ تعداد رکوردهای پردازش شده: {row_count:,}\")\n",
    "    \n",
    "    # مرحله 3: حذف ردیف‌های دارای NaN\n",
    "    print(\"🧹 مرحله 3: حذف ردیف‌های دارای مقادیر خالی...\")\n",
    "    asset_columns = [col for col in output_df.columns if col.startswith('AssetID_')]\n",
    "    before_count = len(output_df)\n",
    "    output_df = output_df.dropna(subset=asset_columns, how='any')\n",
    "    after_count = len(output_df)\n",
    "    print(f\"   حذف {before_count - after_count:,} ردیف دارای مقادیر خالی\")\n",
    "    \n",
    "    # مرحله 4: تبدیل TimeStamp به تاریخ و زمان\n",
    "    print(\"📅 مرحله 4: تبدیل زمان‌ها...\")\n",
    "    output_df['date'] = pd.to_datetime(output_df['TimeStamp'], unit='s')\n",
    "    output_df['RecordDate'] = output_df['date'].dt.date\n",
    "    output_df['RecordTime'] = output_df['date'].dt.time\n",
    "    \n",
    "    # اضافه کردن ستون id\n",
    "    output_df.insert(0, 'id', range(1, len(output_df) + 1))\n",
    "    \n",
    "    # حذف ستون TimeStamp\n",
    "    output_df.drop(columns=['TimeStamp'], inplace=True)\n",
    "    \n",
    "    # مرتب‌سازی بر اساس تاریخ\n",
    "    output_df.sort_values(by='date', inplace=True)\n",
    "    \n",
    "    # مرحله 5: ذخیره در فایل اکسل\n",
    "    print(\"💾 مرحله 5: ذخیره در فایل اکسل...\")\n",
    "    \n",
    "    # تعیین مسیر خروجی\n",
    "    output_dir = r'second_stage_inputs\\G11'\n",
    "    output_file = os.path.join(output_dir, 'dsas_g11_generator_bearings_output.xlsx')\n",
    "    \n",
    "    # ایجاد پوشه در صورت عدم وجود\n",
    "    os.makedirs(output_dir, exist_ok=True)\n",
    "    \n",
    "    try:\n",
    "        output_df.to_excel(output_file, index=False)\n",
    "        print(f\"✅ فایل با موفقیت ذخیره شد: {output_file}\")\n",
    "        print(f\"📊 تعداد رکوردهای نهایی: {len(output_df):,}\")\n",
    "        print(f\"📋 تعداد ستون‌ها: {len(output_df.columns)}\")\n",
    "    except Exception as e:\n",
    "        print(f\"❌ خطا در ذخیره فایل: {e}\")\n",
    "        return None\n",
    "    \n",
    "    # نمایش اطلاعات آماری\n",
    "    print(\"\\n📊 اطلاعات آماری:\")\n",
    "    print(f\"   بازه تاریخ: {output_df['date'].min()} تا {output_df['date'].max()}\")\n",
    "    print(f\"   تعداد AssetIDها: {len(asset_columns)}\")\n",
    "    print(\"\\n📋 نمونه‌ای از داده‌ها:\")\n",
    "    print(output_df.head(10))\n",
    "    \n",
    "    return output_df\n",
    "\n",
    "# اجرای تابع اصلی\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"=\"*60)\n",
    "    print(\"🚀 شروع فرآیند استخراج و تبدیل داده\")\n",
    "    print(\"=\"*60)\n",
    "    \n",
    "    result_df = fetch_and_transform_data()\n",
    "    \n",
    "    if result_df is not None:\n",
    "        print(\"\\n\" + \"=\"*60)\n",
    "        print(\"✅ فرآیند با موفقیت کامل شد!\")\n",
    "        print(\"=\"*60)\n",
    "        \n",
    "        # نمایش نام ستون‌ها\n",
    "        print(\"\\n📋 لیست ستون‌های فایل خروجی:\")\n",
    "        for i, col in enumerate(result_df.columns, 1):\n",
    "            print(f\"   {i:2d}. {col}\")\n",
    "    else:\n",
    "        print(\"\\n❌ فرآیند با شکست مواجه شد!\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
