/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (10000000) [ID]
      ,[AssetID]
      ,[UnitID]
      ,[Value]
      ,[RecordTime]
      ,[RecordDate]
      ,[PersonelID]
      ,[OutofRange]
      ,[ValueType]
      ,[MobileID]
      ,[DateTime]
      ,[TimeStamp]
      ,[Job]
      ,[IsDeleted]
      ,[ShiftCode]
      ,[OnTime]
  FROM [DSAS].[PDA].[Periodic_Values]
  Where [UnitID]=11 and
  ([AssetID]=9357 or [AssetID]=9343 or [AssetID]=9344 or [AssetID]=9362 or [AssetID]=9363 or [AssetID]=9364 or [AssetID]=9365 or [AssetID]=9366 or [AssetID]=9367 or [AssetID]=9371 or [AssetID]=9372 or [AssetID]=9373)