/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (10000000) [ID]
      ,[AssetID]
      ,[UnitID]
      ,[Value]
      ,[RecordTime]
      ,[RecordDate]
      ,[PersonelID]
      ,[OutofRange]
      ,[ValueType]
      ,[MobileID]
      ,[DateTime]
      ,[TimeStamp]
      ,[Job]
      ,[IsDeleted]
      ,[ShiftCode]
      ,[OnTime]
  FROM [DSAS].[PDA].[Periodic_Values]
  Where ([AssetID]=12697)